### ISSUE TITLE
Add more entities

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#1]
These entities are/may be using cname:
```
a8.net
ad-cloud.jp
ebis.ne.jp
genieespv.jp
```
`genieespv.jp` tracker are already blocked by regex yet still good to add domains for DNS.

**Comment by ameshkov** [comment]
Could you please also mention what companies do these trackers belong to?

**Comment by Yuki2718** [comment]
@ameshkov 
`a8.net` -> `a8.net`: one of the largest affiliate service in Japan (`https://www.a8.net/`)
`ad-cloud.jp` -> GMO Internet Group: (`https://www.gmo.jp/`)
`ebis.ne.jp` -> AD EBiS: effectiveness measurement of ads (`https://www.ebis.ne.jp/`)
`genieespv.jp` -> GENIEE: one of the largest SSP provider in Japan also providing DSP: (`https://geniee.co.jp/`)

**Comment by ameshkov** [comment]
@Yuki2718 got it, thank you, we'll try these 4 tomorrow.

Meanwhile, if you have any other trackers in your mind, please let us know.

**Comment by ameshkov** [comment]
Quick update on a8.net -- not too many found:
```
    "cloaked_trackers": [
        {
            "disguise": "a8.shopserve.jp",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8cv.omni7.jp",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8.cyclemarket.jp",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8clk.waq-online.com",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8clk.world-family.co.jp",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8clk.www.autoway.jp",
            "tracker": "trck.a8.net"
        },
        {
            "disguise": "a8clk.xserver.ne.jp",
            "tracker": "trck.a8.net"
        }
    ]
```
