### ISSUE TITLE
[not a bug][trackers] Found an adsafeprotected (IAS) disguised tracker on www.tf1.fr

### ISSUE THREAD

**Issue by K-mikaZ** [AdguardTeam/cname-trackers#101]
CNAME:
> `static.adsafeprotected.com => d162h6x3rxav67.cloudfront.net`

disguised trackers redirect to `/skeleton.gif` (found on `www.tf1.fr/tf1/direct`)

I propose blocking `||d162h6x3rxav67.cloudfront.net^`

**Comment by jellizaveta** [comment]
Hello. I have been watching this tracker for a week and so far only one disguised domain `static.adsafeprotected.com` has been found for this tracker 
I don't think it's worth adding it to the lists for now.
