### ISSUE TITLE
Add greylabeldelivery.com, Stape and WeCanTrack

### ISSUE THREAD

**Issue by max-ostapenko** [AdguardTeam/cname-trackers#105]
Based on [HTTP Archive](https://httparchive.org/) data analysis (similar to #102 ) there were some trackers identified, that are missing in the list:

Company | CNAME Domain | Disguised hostname examples
-- | -- | --
??? | *.greylabeldelivery.com | tagdelivery.mayoclinic.org, tags.kmart.com.au.greylabeldelivery.com
WeCanTrack | *.wecantrack.com | wct.softonic.com
Stape | *.stape.net | load.gr4n1t3.rubix.com, gtm.liberatigioielli.com

Please add.

**Comment by jellizaveta** [comment]
Hello. [greylabeldelivery](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/refs/heads/master/data/trackers/content-ignite.txt), [Stape](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/refs/heads/master/data/trackers/stape.txt), [Wecantrack](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/refs/heads/master/data/trackers/wecantrack.txt) was added to config.

Thank you for your contribution!
