### ISSUE TITLE
CNAME tracker of log.ma-jin.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#11]
URL: `https://www.tus.ac.jp/`
ma-jin is a marketing-automation tool by Geniee (`https://geniee.co.jp/`) : `https://ma-jin.jp/`
https://github.com/AdguardTeam/AdguardFilters/commit/7b28d773f5b91dd880b306b07a0ae24f9b7754aa

**Comment by ameshkov** [comment]
Let's see how many trackers will be found for it.
