### ISSUE TITLE
QuinStreet

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/cname-trackers#16]
Both www.moneyrates.com & www.quinstreet.com map to www.quinstreet.com.edgekey.net.  Current DNS filters only block via `||quinstreet.com` & so only catch 2nd domain, but this feels like a 2nd-iteration CNAME, & should catch 1st, as well.  But _that_ seems like it could false positive other domains of the pattern, as well.  What's best way to catch these kind of scenarios?  Right now, I'm just using user DNS filter `||quinstreet.`, which catches all of the above.

**Comment by ameshkov** [comment]
As I recall, `edgekey.net` is a domain that belongs to Akamai, i.e. this is a CDN, not a tracker. It's also rather normal for different domains to map to a CDN edge.

**Comment by TPS** [comment]
I don't mean `edgekey.net` but `quinstreet.com.edgekey.net`, which I think _is_ related to `moneyrates.com` as `quinstreet.com` is blocked all over it.  To me, _that_ feels like `quinstreet.com.edgekey.net` is the base to be blocked, & then the others would be blocked by CNAME rules.  Am I wrong?

**Comment by ameshkov** [comment]
Yeah, that's right, if you have it in the DNS filter, it will be blocked as a CNAME as well.

Here's the full list of domains that are CNAME'd there:
```
accounts.bestrates.com
autoinsurance.insure.com
rates.savingsaccounts.com
root.carinsurance.com
secure.amone.com
www.amone.com
www.cardratings.com
www.carinsurance.com
www.databasejournal.com
www.doorandwindow.com
www.improvementcenter.com
www.insurance.com
www.insure.com
www.moneyrates.com
www.oldhouseweb.com
```

I wonder what are these? Is this an ad network or is this just a single publisher using different domains?

**Comment by TPS** [comment]
So, https://en.m.wikipedia.org/wiki/CardRatings.com leads 1 to https://en.m.wikipedia.org/wiki/QuinStreet, which means all those sites, similar to my concerns in https://github.com/AdguardTeam/HttpsExclusions/issues/24, perhaps @ 1 point _were_ legit sites, but now are part of a web of ad/affiliate/tracking network.

**Comment by ameshkov** [comment]
Tbh, it does not seem as an ad network. Moreover, `www.insure.com` is just a website.

I suppose Akamai works just like Cloudflare, i.e. this `quinstreet.com.edgekey.net` is just a proxy that proxies traffic depending on the request's domain. For one domain it may proxy it to some tracker, for some other domain it may proxy it to a legit web server.

**Comment by TPS** [comment]
https://en.m.wikipedia.org/wiki/QuinStreet#History lists those & more as QuinStreet aquisitions.  Perhaps they're just using the Google playbook by funding legit business via mainly they're own ad network, but I've bumped into those "comparisions" labeled as advertising.
