### ISSUE TITLE
Modified-Date field should be published

### ISSUE THREAD

**Issue by markster101** [AdguardTeam/cname-trackers#19]
Its a request, but I would suggest that you include Last-Modified as part of your publish request-header.
Most lists include that for the subscribers to determine if and when the list has been updated and only perform complete download of the list if Last-Modified date has changed. 

As an example based on Stevenblack list:

curl -I http://sbc.io/hosts/hosts
HTTP/1.1 200 OK
Cache-Control: max-age=86400
Content-Length: 2785346
Content-Type: text/plain
**Last-Modified: Fri, 01 Oct 2021 02:00:34 GMT**
Accept-Ranges: bytes
ETag: "0dc81e68b6d71:0"
Server: NginX
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: ASP.NET
Date: Sat, 02 Oct 2021 18:48:01 GMT

**Comment by slavaleleka** [comment]
done
