### ISSUE TITLE
Question: possible false positive for sol.sfc.keio.ac.jp?

### ISSUE THREAD

**Issue by koluke** [AdguardTeam/cname-trackers#24]
Hi, seems like there may be a false positive for `sol.sfc.keio.ac.jp`.  It's being flagged as CNAME cloaking for Adobe Experience Cloud according to:
https://github.com/AdguardTeam/cname-trackers/blob/39cd5f7250ea99bb537973c229bcca598437a617/trackers/adobe-experience-cloud-(formerly-omniture).json#L4177

However, the site is a set of A/AAAA records that both resolve to IP addresses.  (The site itself is a learning management system in use at my university hosted on [Canvas LMS](https://github.com/instructure/canvas-lms), which as far as I know doesn't use any internal tracking either).

**Comment by ameshkov** [comment]
Definitely a false positive.

We've got some yesterday, the situation should normalize when we rebuild the list.

**Comment by koluke** [comment]
Great, thanks for the quick clarification!
