### ISSUE TITLE
fastmailusercontent.com being blocked - should not be

### ISSUE THREAD

**Issue by jasonekratz** [AdguardTeam/cname-trackers#25]
fastmailusercontent.com's whole point is to avoid tracking by loading images via a proxy. So now when I want to see images in email I can't unless I turn off everything for Fastmail.

**Comment by ameshkov** [comment]
We've got some false-positives in the list yesterday, the issue should go away soon when we rebuild it.

**Comment by jasonekratz** [comment]
Thanks much Andrey!

**Comment by ameshkov** [comment]
Done
