### ISSUE TITLE
Remove specopssoft subdomain

### ISSUE THREAD

**Issue by Faflu** [AdguardTeam/cname-trackers#26]
Hi,
Please, remove from your list info.specopssoft.com - this is a legitimate subdomain of specopssoft.com, which is not included in your list.

**Comment by slavaleleka** [comment]
note please that **AdGuard cname-trackers** is not a blocklist, it's just a list of cloaked trackers

and `info.specopssoft.com` is a real cname for tracker `go.pardot.com`
