### ISSUE TITLE
Add popcashjs.b-cdn.net cname adservers

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#28]
https://github.com/AdguardTeam/AdguardFilters/pull/100496#issuecomment-1038208503

I forgot to take a note but I saw `cdn.eeco.xyz/app.js` too somewhere today.

**Comment by ameshkov** [comment]
`popcashjs.b-cdn.net` this domain actually belongs to BunnyCDN, it seems PopCash is using it to serve their ad scripts.

@slavaleleka I think we can safely add it right away.
Moreover, the resulting file probably can be included into AdGuard Base filter.

**Comment by Yuki2718** [comment]
`cdn.jwalf.com` (=> `popcashjs.b-cdn.net`) on `moviecrumbs.net` is unblocked.

**Comment by slavaleleka** [comment]
`cdn.jwalf.com` will be added after next cname-trackers build
