### ISSUE TITLE
Add justdomains and combined lists versions

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/cname-trackers#3]
@ameshkov per you request just making it official as discussed in [StevenBlack's Repo](https://github.com/StevenBlack/hosts/issues/1563#issuecomment-791337578).
Let us know when ready. Thank you 👍

**Comment by reinerotto** [comment]
+1. 
Plain list would be very appreciated, for simple inclusion into hosts file

**Comment by ameshkov** [comment]
@slavaleleka let's do the following:

1. Add `_justdomains.txt` files for each tracker.
2. Add `combined.txt` and `combined_justdomains.txt` files and concatenate all trackers' files there.

**Comment by ameshkov** [comment]
@slavaleleka I've added combined lists manually for now - just for you to see the desired result: https://github.com/AdguardTeam/cname-trackers#the-lists

Note, that we should use `#`-style comments in the "justdomains" versions.

**Comment by dnmTX** [comment]
@ameshkov is this ready to go or it's still in a draft pfase? Not trying to rush things here,rather checking on the progress 👍

**Comment by ameshkov** [comment]
@dnmTX it's not automated yet, but anyways, the draft version is valid anyway.
