### ISSUE TITLE
Add extole.com CNAME tracker

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#31]
Found on `www.ancestry.com`: `https://refer.ancestry.com/core.js` (=> `ancestrydna.extole.com`)
Refer-a-friend marketing so not pure tracker tho: `https://www.extole.com/`.

**Comment by Yuki2718** [comment]
`extole.io` case on `www.2ndswing.com` (`https://refer.2ndswing.com/core.js` => `2ndswing.extole.io`)

**Comment by jellizaveta** [comment]
Added `||extole.io^$third-party` in TPF
