### ISSUE TITLE
apply for https://ads.shopee.sg/

### ISSUE THREAD

**Issue by COOKIES-LGL** [AdguardTeam/cname-trackers#40]
"https://ads.shopee.com.br/",
"https://ads.shopee.tw/",
"https://ads.shopee.sg/",
"https://ads.shopee.com.my/",
"https://ads.shopee.vn/",
"https://ads.shopee.co.th/",
"https://ads.shopee.ph/",
"https://ads.shopee.cn/",
"https://ads.shopee.kr/",
"https://ads.shopee.com.mx/

Above lists our affected sites,
Our site will be intercepted by the $popup rules
While we can open our sites by in the address bar, we cannot open them through new windows, especially for AdGuard interceptors.

The sites above are actually block, and although we use the CDN to record the static resources, we still can't use the site properly

![截屏2022-04-13 下午5 12 48](https://user-images.githubusercontent.com/52285315/163142650-3763fa16-da0a-49ce-a697-3b7e2fb1c950.png)

OS/version: mac
Browser/version: Chrome: version 98
Adblock Extension/version: AdGuard: version 4.0.141

I really hope that you can reply to us
I wish you a happy work

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers `://ads.$popup` seems to be an overkill, isn't it?

**Comment by AdamWr** [comment]
Okay, I have removed this rule.

**Comment by COOKIES-LGL** [comment]
First of all, thank you for your reply. When will the rules come into effect?
I have also mentioned PR to eastlist before, but it was not adopted,
What is the way to submit changes to easylist?
Looking forward to your answer @AdamWr

**Comment by AdamWr** [comment]
>When will the rules come into effect?

Filters update should be available now, please update filters in settings in AdGuard extension.

>I have also mentioned PR to eastlist before, but it was not adopted,
>What is the way to submit changes to easylist?

You can report it here - https://github.com/easylist/easylist/issues

**Comment by COOKIES-LGL** [comment]
hi @AdamWr  thanks for your reply 

and tomorrow i have made a PR for easylist and have been merged .

but No update was made on the rules

![截屏2022-04-15 下午12 15 16](https://user-images.githubusercontent.com/52285315/163517268-4c73edbd-68c5-447d-bf3b-4e1afe750d95.png)

![截屏2022-04-15 下午12 14 58](https://user-images.githubusercontent.com/52285315/163517274-17408cb2-4153-437a-bdbe-d6c72d51cdab.png)

When will the rules come into effect?

Looking forward to your answer

**Comment by AdamWr** [comment]
In theory it should be available after about 1-2 hours after pull request has been merged, but it seems that it's not yet.
I guess that these changes should be available in a few hours.

**Comment by AdamWr** [comment]
It seems that I was wrong and update was available, but it looks like that `~ads.shopee.com.br` (I have checked this website) has not been added to exception here - https://github.com/easylist/easylist/commit/1fd56ea53d54aaaf820ccea911f6cfc8ff642ad4

**Comment by COOKIES-LGL** [comment]
OH, @AdamWr  Thanks so much for your reminder, I submitted the PR again.

[11680](https://github.com/easylist/easylist/pull/11680)
