### ISSUE TITLE
Just block `actonservice.com`

### ISSUE THREAD

**Issue by prajwal-koirala-0000** [AdguardTeam/cname-trackers#42]
There is 656 entries of randomly generated subdomains for this given domain, instead of trying to identify each sub-domain, we should block the whole domain.

**Comment by Yuki2718** [comment]
No example and no explanation => no action

**Comment by Yuki2718** [comment]
`ids.actonservice.com` has bunch of contents, not tracker e.g. `https://ids.actonservice.com/acton/fs/blocks/showLandingPage/a/11314/p/p-0033/t/page/fm/0`, `https://ids.actonservice.com/acton/media/11314/mortgagedocprep`

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/1bd260c1b065200fda28ec95ce14647f973fb029/SpywareFilter/sections/cname_trackers.txt#L18
