### ISSUE TITLE
Add we-stats.com CNAME tracker

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#49]
`https://bup.bankofamerica.com/client/v3.1/web/wup?cid=barbie` (=> `wup-532e636f.us.v2.we-stats.com`) on `www.bankofamerica.com`
`we-stats.com` is currently blocked by EP but not by AGTPF. Seen on `https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification` and will add soon, but I have no idea who is behind this analytics domain.

**Comment by Alex-302** [comment]
Not sure about that.
We have some exclusions
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/511e7362703a4af4d509c21eb8589140a3409bb4/Filters/exceptions.txt#L60-L63
It seems this is related to anti-fraud and used by banks only, not for marketing.

**Comment by Yuki2718** [comment]
Anti-fraud provider often uses fingerprinting, which should not be the case TBH, but probably best not to block them.
