### ISSUE TITLE
add combined_disguised_trackers.json

### ISSUE THREAD

**Issue by ghostwords** [AdguardTeam/cname-trackers#5]
Following up on https://github.com/AdguardTeam/cname-trackers/issues/4#issuecomment-793148173

Could you also provide (and maintain) a JSON that maps between first party domains and CNAME domains?

Something like:

```javascript
{
  "abc.some-first-party.com": "xyz.potential-tracker.com",
   ...
}
```

In cases of multiple CNAME records, could you provide just the one entry for the domain at the end of the chain (https://github.com/AdguardTeam/cname-trackers/issues/4#issuecomment-796918623)?

The basic idea here is to enable canonical name lookups for a set of domains. The answers provided by the JSON should match answers provided by the [`dns.resolve()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve) API.

For example:
```javascript
browser.dns.resolve("alsgaj.chosun.com", ['canonical_name']).then(r=>{console.log(r.canonicalName)})
// prints gum.va1.vip.prod.criteo.com (not a.dnsdelegation.io)
```

**Comment by spirillen** [comment]
Let me share some thought on this. @Somebodyisnobody is actually cooking on a "Domain list exchange format" at <https://www.mypdns.org/T3776>, which I think could be good to have a look at, before building a lot of new "sources" as the hole idea is we get a standard for sharing information's between lists maintainers/users/projects

**Comment by ameshkov** [comment]
@ghostwords sorry for the long wait, just added JSON versions: https://github.com/AdguardTeam/cname-trackers/tree/master/trackers

**Comment by ghostwords** [comment]
Thank you!

Could you add (and maintain) a single combined JSON mappings list? I should have been more clear; sorry for the misunderstanding.

**Comment by ameshkov** [comment]
Yep, shouldn't be a problem.

**Comment by slavaleleka** [comment]
@ghostwords check it out:
https://github.com/AdguardTeam/cname-trackers/blob/master/combined_disguised_trackers.json

**Comment by ghostwords** [comment]
I noticed a few discrepancies between your data and my own `nslookup`s.

[`click.yahoosmallbusiness.net` is mapped to `forpci1.actonsoftware.com`](https://github.com/AdguardTeam/cname-trackers/blob/627dfb950ffd9e56aee7eeb4cbd23b17785d0cf3/trackers/act-on.json#L114-L115) but `nslookup` comes back with  `mkto-ab370049.com`.

A few domains in your data like `stats.geekzone.co.nz` no longer resolve to anything.

I also get a different load balancer for a few thousand entries. For example, `gum.am5.vip.prod.criteo.com` vs. `gum.va1.vip.prod.criteo.com`.

Are these all expected as DNS records change while your data is a snapshot from a particular point in time?

**Comment by ameshkov** [comment]
> Are these all expected as DNS records change while your data is a snapshot from a particular point in time?

Most likely it is, but we'd better double-check this. Let me reopen it just in case.

**Comment by ameshkov** [comment]
@ghostwords yeah, after all, that's okay that you're getting a different entry. We're seeing many of them, they may change randomly, so we just pick a random one.
