### ISSUE TITLE
Add rdtk.io CNAME tracker

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#54]
e.g. On `www.cabazes.pt`
`https://track.hoodeffect.com/uniclick.js?defaultcampaignid=627e170335981a0001d4dc76&attribution=lastpaid&regviewonce=false&cookiedomain=cabazes.pt&cookieduration=30` (=> `sin.rdtk.io`)
On `elevecosmetics.com`
`https://track.ogrowthlabs.com/uniclick.js?defaultcampaignid=61a116aac056b300014a547a&attribution=lastpaid&regviewonce=false&cookiedomain=elevecosmetics.com&cookieduration=30` (=> `sin.rdtk.io`)
`||rdtk.io^` is in EasyList.

Maybe `://track.*/uniclick.js` and `://track.*/events.js` can catch most of them.

**Comment by TPS** [comment]
Also, from https://www.malwarebytes.com/blog/detections/rdtk-io:
> The domain rdtk.io was blocked by Malwarebytes because it was associated with [malvertising](https://www.malwarebytes.com/blog/glossary/malvertising/).

**Comment by TPS** [comment]
Per https://docs.redtrack.io/knowledgebase/adding-custom-domain/, this is a domain purely for tracking, especially via `CNAME`.
