### ISSUE TITLE
[FP] self.events.data.microsoft.com

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/cname-trackers#57]
Endpoint self.events.data.microsoft.com is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

**Comment by slavaleleka** [comment]
note please that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers

and `self.events.data.microsoft.com` is an actual cname for tracker domain `self-events-data.trafficmanager.net` which is used by `ghochv3eng.trafficmanager.net`
