### ISSUE TITLE
Split cname domains data to ads and trackers

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/cname-trackers#60]
all fetched data is stored to `trackers` directory now. and some of them is used not for trackers but ads

we can add extra property for config.json input objects which will be used for collecting to different directories

```
{
    "company_name": "Clickaine",
    "type": "ad",
    "domains": [
        "api.clickaine.com"
    ]
},
{
    "company_name": "Commanders Act",
    "type": "tracker",
    "domains": [
        "tagcommander.com"
    ]
},
```

**Comment by TPS** [comment]
Could #51 be implemented simultaneously?

**Comment by slavaleleka** [comment]
@TPS no sure

**Comment by TPS** [comment]
> @TPS no sure

@slavaleleka What do you mean?

**Comment by slavaleleka** [comment]
I mean that we may resolve the issues separately
