### ISSUE TITLE
false positive entry

### ISSUE THREAD

**Issue by hyder365** [AdguardTeam/cname-trackers#62]
Hi. In the following DNS list:

https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt

The domain "services.chipotle.com" is listed. Having that domain blocked breaks the online food ordering functionality of the website.

**Comment by ameshkov** [comment]
Please note that this list should not be used as a blocklist if you want to avoid false positives like that.

The purpose of that list is to show which third-parties are disguised as first-parties. It is up to the downstream blocklists to filter out false positives.
