### ISSUE TITLE
content.lansweeper.com

### ISSUE THREAD

**Issue by Leo-Lansweeper** [AdguardTeam/cname-trackers#66]
We have some clients who use this tool and are having trouble with our emails and domains. Just trying to figure out where to begin to resolve this.

1. through you
2. through Adguard
3. IT investigating our domain for cloaked tracking

Any info would be appreciated. Thank you.

**Comment by dnmTX** [comment]
> Just trying to figure out where to begin to resolve this.

How about here:
![Capture](https://user-images.githubusercontent.com/34774426/217401582-3abff274-d2d2-4e7e-8755-99afb01373cf.PNG)

https://www.techtarget.com/whatis/definition/Pardot
😉

**Comment by slavaleleka** [comment]
note please that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers
