### ISSUE TITLE
Should click.redditmail.com be whitelisted?

### ISSUE THREAD

**Issue by amano-kenji** [AdguardTeam/cname-trackers#68]
Because emails sent by reddit.com contain links to click.redditmail.com, I can't open email links sent by reddit.com.

**Comment by amano-kenji** [comment]
What do you suggest as an alternative? Something that automatically strips click.redditmail.com?

**Comment by TPS** [comment]
I don't subscribe to Reddit e-mail notifications, so I don't know how *they*'re structured.  But, if stripping would work (transparent tracking), of course that's the way to go.

But many are now opaque trackers: 1 has to resolve the redirecting URL to get the final 1.  That's a much thornier problem I've yet to see a good (= easy & privacy-preserving) solution for.  When _I_ have such, I will generally search the given *meta*data from the notification in a private browser/tab & hope for the best.🤞🏾  That works >90% of the time for me, so, until something better is available to me, it's "good enough."

**Comment by amano-kenji** [comment]
Okay, closing it. I am going to implement my own URL handler that strips trackers automatically.

**Comment by TPS** [comment]
@amano-kenji Don't let _me_ stop you, but perhaps (1st?) look @ https://github.com/svenjacobs/leon for case 1 & https://github.com/svenjacobs/leon/discussions/80 for case 2.

**Comment by TPS** [comment]
> But, if stripping would work (transparent tracking), of course that's the way to go.

> perhaps (1st?) look @ https://github.com/svenjacobs/leon

@amano-kenji I've finally run into my own example of this & can confirm it's a type-1 case of simple stripping/decoding.  Did you get anywhere w/ this?  Else, I can recommend perhaps [submitting a sanitizer PR for Léon](https://github.com/svenjacobs/leon/pulls?q=is%3Apr) as @svenjacobs has worked to make it simple to do so.  There's now even [an issue for Reddit links](https://github.com/svenjacobs/leon/issues/170).

**Comment by amano-kenji** [comment]
Actually, I haven't bothered after https://github.com/notracking/hosts-blocklists/issues/700

**Comment by amano-kenji** [comment]
But, you have to use a URL handler if you want cleaning.
