### ISSUE TITLE
remove wl.spotify.com because it's needed for Spotify data request

### ISSUE THREAD

**Issue by thomasmerz** [AdguardTeam/cname-trackers#71]
This domain is needed to "confirm your Spotify data request". By whitelisting this domain I was able to "confirm my Spotify data request". So why is this being blocked here?

See also:
https://github.com/StevenBlack/hosts/issues/1727, https://github.com/StevenBlack/hosts/issues/2021 and https://github.com/RPiList/specials/issues/998

**Comment by ameshkov** [comment]
The problem is that cname-trackers is build completely automatically and we don't do exclusions here.

The lists that use cname-trackers as a source should do it on their own.

**Comment by thomasmerz** [comment]
As far as I understood https://www.netify.ai/resources/domains/bnc.lt
>  Branch IO - Advertiser
Branch is a mobile measurement and deep linking platform, used by the most top ranking apps to increase efficiency and revenue.

Conclusion:
Users have to whitelist wl.spotify.com by selfself if they need it for some reason.
