### ISSUE TITLE
Incorrect RZP format

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/cname-trackers#73]
In order to be standard RPZ format we need to include proper header into the file. This will allow certain program to properly detect if downlaod file is rpz file.  Havining only CNAME . string is not enough to be standard rpz file.
eg:

$TTL 6h
@ IN SOA AdguardTeam.local. (741328541 6h 1h 1w 2h)
  IN NS  localhost.

**Comment by markster17** [comment]
This file (https://github.com/AdguardTeam/cname-trackers/blob/master/combined_disguised_ads_rpz.txt) is supposed to be rpz file. But it is not a standard rpz format. It needs proper file header. Simply insert what I suggested as first 3 lines in the file.

**Comment by Alex-302** [comment]
@jellizaveta 
Description is in https://www.isc.org/docs/BIND_RPZ.pdf `#3`

<details>
<summary>Example with comments</summary>

```
$TTL 300

@		IN SOA  localhost. need.to.know.only. (
                       201702121 ; Serial number
                       60        ; Refresh every minute
                       60        ; Retry every minute
                       432000    ; Expire in 5 days
                       60 )      ; negative caching ttl 1 minute
		IN NS   LOCALHOST.

deteque.com			IN CNAME rpz-passthru.
*.deteque.com			IN CNAME rpz-passthru.
spamhaus.org			IN CNAME rpz-passthru.
*.spamhaus.org			IN CNAME rpz-passthru.
32.25.195.194.32.rpz-ip		IN CNAME rpz-passthru.		; whitelist 34.194.195.25/32
32.71.219.156.35.rpz-ip		IN CNAME rpz-passthru.		; whitelist 35.156.219.71/32

example.com			IN CNAME .			; local block against example.com
*.example.com			IN CNAME .			; local block against example.com
```

</details>

**Comment by jellizaveta** [comment]
@markster17 Could you provide a little more information about the usage problem? In which program are you using the `rpz` file format, maybe some steps to reproduce, file reading errors or something like that

**Comment by Alex-302** [comment]
@markster17 But user can use own parameters, just merge a file with header with downloaded file (not by hand, of course).
