### ISSUE TITLE
unbound error: parse failure combined_disguised_trackers_rpz.txt (Domainname length overflow)

### ISSUE THREAD

**Issue by K-mikaZ** [AdguardTeam/cname-trackers#74]
unbound.exe
error: parse failure [raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_rpz.txt](https://github.com/AdguardTeam/cname-trackers/blob/master/combined_disguised_trackers_rpz.txt)
Domainname length overflow:
`buaabcxnyyddcho3bryijpv35nlvl3qrc6dcbagto6nizqzz.glnmtpa2efncoxok56c2earmvivotvbm5yxkagsm42yymxhk.jax2a74phpxvngrdy7bo6e5ltucxcve2jbswhoxi4ottreez.mcrhmxkqlzko5f36ul337smzeilgxb7lgyj2tuolm53of6dd.wfvmv7uekjmrrusl.er.tt.omtrdc.net CNAME .`

**Comment by TPS** [comment]
Huh, that looks like a domain _designed_ to trigger something.

But, iiuc, it's a legal domain, so maybe check / cross-post this w/ https://github.com/NLnetLabs/unbound/issues ?

**Comment by slavaleleka** [comment]
please note that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers

`buaabcxnyyddcho3bryijpv35nlvl3qrc6dcbagto6nizqzz.glnmtpa2efncoxok56c2earmvivotvbm5yxkagsm42yymxhk.jax2a74phpxvngrdy7bo6e5ltucxcve2jbswhoxi4ottreez.mcrhmxkqlzko5f36ul337smzeilgxb7lgyj2tuolm53of6dd.wfvmv7uekjmrrusl.er.tt.omtrdc.net` is a legal domain name
https://uploads.adguard.org/slbdzdrvxvcs8.png
