### ISSUE TITLE
AdGuard CNAME disguised trackers list has wildly increased the number of rules

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/cname-trackers#75]
Probably an increase of about 300,000 rules.
Any problems?
Or is this correct?

![3](https://github.com/AdguardTeam/cname-trackers/assets/44166263/c5fa9019-9f39-45b9-bdd2-344611feda5e)

**Comment by slavaleleka** [comment]
looks legal to me, and you can check it yourself by `nslookup` for any domain in the list

btw we are working on https://github.com/AdguardTeam/cname-trackers/issues/51 so eventually there will be separated combined lists for different categories

**Comment by SampeiNihira** [comment]
Hi,
can you explain the difference with the CNAME disguised **ads** list which has about 23000 rules?

**Comment by Yuki2718** [comment]
> I haven't seen CNAME disguised adservers are used for other than ads,

Maybe one reason of this will be, while some of listed providers in CNAME disguised trackers are general tech companies (ex. Adobe), many of CNAME adserver providers currently included are pure advertising companies (ex. Adspyglass, Popcash).

**Comment by SampeiNihira** [comment]
Yuki,you will notice that UBO removes about 1000 rules from the CNAME Ads list alone.
The CNAME trackers rules used are almost all of them.

Isn't this "splitting method" confusing?

**Comment by Yuki2718** [comment]
I don't know what the splitting method means. There's no priority/order in uBO's de-duplication, maybe uncheck the list and recheck will change the status.

**Comment by slavaleleka** [comment]
> The CNAME filter lists moreover have the exact same title

@SampeiNihira could you please create a new issue for that?

**Comment by slavaleleka** [comment]
@SampeiNihira 
btw there are new separated combined lists now:
https://github.com/AdguardTeam/cname-trackers/tree/master/data

and combined files from the root directory shall be removed eventually

**Comment by Yuki2718** [comment]
@slavaleleka BTW I guess we should also refine README and clarify disguised_ads is not a part of EasyPrivacy or Tracking Protection filter but of Base filter.

**Comment by SampeiNihira** [comment]
@slavaleleka

I am trying in Edge the CNAME combined_disguised_microsites.txt filter list.
I am not concerned about any websites not working.

A better explanation to the paragraph would also be interesting:

The lists

https://github.com/AdguardTeam/cname-trackers#the-lists
