### ISSUE TITLE
Disguised trackers list may contain invalid rules

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/cname-trackers#77]
there are some strange rules
```
||*.b2bmktg.com^

||-01-car21c-f8news.net.daraz.com^
||-043ns41.net.daraz.com^
||-084-gls-223-www-9-k-0brasil.net.daraz.com^
||-1-astrologie-api1-www-cf96sept.net.daraz.com^

_tcp.academyofconsciousleadership.net
webdisk-staging.-dev.tt.omtrdc.net
```

original issue: https://github.com/AdguardTeam/AdguardForWindows/issues/4768

**Comment by Aydinv13** [comment]
@WinCHM

Не могли бы вы экспортировать ваши логи и настройки и прислать на devteam@adguard.com? 
Экспорт логов:
**Настройки - Основные настройки - Экспортировать логи**
Экспорт настроек:
**Настройки - Основные настройки - Экспортировать настройки**

**Comment by WinCHM** [comment]
@Aydinv13 

Я заменил https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers.txt на https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads.txt

Данную ссылку предоставил **Murder302** - https://forum.ru-board.com/topic.cgi?forum=5&bm=1&topic=50480&start=2620#lt

После замены ссылки на фильтр проблема ушла и теперь все в порядке.

**Comment by slavaleleka** [comment]
domains like `_.tt.omtrdc.net` or `*.exaapi.com` are being resolved by [Node's DNS](https://nodejs.org/api/dns.html) just fine
