### ISSUE TITLE
add fastly.net

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/cname-trackers#79]
```
;; ANSWER SECTION:
data-cdn.theatlantic.com. 43200	IN	CNAME	na-eu.atlanticmedia.map.fastly.net.
```
https://urlfilter.adtidy.org/v1/findCloaked?domain=fastly.net&oid=2c98c0fb-67d1-9671-4693-822c360caf4a

Related to https://github.com/AdguardTeam/AdguardFilters/issues/158363

**Comment by yoshimo** [comment]
Isn't this just a CDN provider? Feels like you'll get a lot of false positives as a result.

**Comment by jellizaveta** [comment]
it might be worth adding just specific domains

**Comment by jellizaveta** [comment]
I found no evidence to support my guess
