### ISSUE TITLE
Outright remove pardot tracker

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/cname-trackers#8]
They were initially not added for the amount of trouble (https://github.com/AdguardTeam/AdguardFilters/pull/76213#issuecomment-788918255) and now causing lots of - I showed a few examples in List Authors Chat. There should be many more.

**Comment by ryanbr** [comment]
Should list them here, I'm not sure removing them outright would be a good idea. Maybe tweak the rules?

**Comment by Yuki2718** [comment]
Click-through or direct page:
```
biz-sol.sony.jp ( http://www.hoteresonline.com/articles/6971 )
cs.cloudsign.jp ( https://www.cloudsign.jp/ )
go.ndbb.jp ( https://go.ndbb.jp/l/701623/2020-10-06/4vd3s )
go.newton-consulting.co.jp ( https://go.newton-consulting.co.jp/HP/geje_10year/ )
go.procommit.co.jp ( https://go.procommit.co.jp/header_scroll?utm_referrer=https%3A%2F%2Fwww.procommit.co.jp%2F )
```
Submission form broken:
`go.anets.co.jp` at `https://www.anets.co.jp/rakura-cloud/`
Links to digital 
`adm.tyg.jp` at `https://www.tyg.jp/` (popup menu, may be hard to find)
The last two cases are not even tracker. When just a quick check only on jp domain returns this number of problems, we should expect there are many more actually.

> Maybe tweak the rules?

But how, as a nature of cname tracker we can't use `$third-party`. Maybe if there's a common pattern in the tracker.

**Comment by ameshkov** [comment]
Guys, this repo is NOT supposed to be used as a blocklist, it just shows what's what in reality.

You can include parts of the lists, there's no obligation to include every tracker here (moreover, this would definitely cause troubles).

If `go.pardot` is causing troubles, there're two safe options:

1. Not include it at all into EasyPrivacy, like we do with the Tracking Protection filter: https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/cname_trackers.txt#L53
2. Tweak the rules as @ryanbr suggests.

> But how, as a nature of cname tracker we can't use $third-party. Maybe if there's a common pattern in the tracker.

Limit it to `$script` maybe?

**Comment by ameshkov** [comment]
Closing since removing anything is not an option, but let's continue the discussion.

**Comment by Yuki2718** [comment]
@ameshkov Okay, sorry for my confusion.
@ryanbr  Limiting to `$script` still doesn't solve the issue at `https://www.tyg.jp/` so I vote for the option 1.

**Comment by ameshkov** [comment]
We could probably apply `$cookie` modifier to those domains, but this needs to be tested.
