### ISSUE TITLE
In `README`, screenshots with light backgrounds are very unpleasing to eye when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/cname-trackers#81]
### Problem Description

In the [README](https://github.com/AdguardTeam/cname-trackers#readme), screenshots with light backgrounds are very unpleasing to the eye when using the dark theme in GitHub.

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/cname-trackers/assets/19418601/5130fc38-73a5-44e8-a46c-dde234279ec7)

</details>

### Proposed Solution

Add screenshots of the app's dark theme when using dark theme on GitHub.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by slavaleleka** [comment]
done 🎉
