### ISSUE TITLE
Please, fix this

### ISSUE THREAD

**Issue by SGirl-Zockt** [AdguardTeam/cname-trackers#82]
[i] Target: https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 11021 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "||*.exaapi.com^"

  [i] List has been updated

**Comment by jellizaveta** [comment]
domain`*.exaapi.com ` resolves by node.js

**Comment by jellizaveta** [comment]
@SGirl-Zockt Could you please specify which wild-card format is appropriate for your blocker?

**Comment by SGirl-Zockt** [comment]
I use the Pi-Hole
The Pi-Hole use this Format
||0bi.de^

**Comment by Alex-302** [comment]
@SGirl-Zockt You can just ignore this rule. It is not supported by Pi-Hole, but syntactically correct. We use AdBlock-style syntax.

**Comment by slavaleleka** [comment]
@SGirl-Zockt 
please note that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers. there are lists of rules for various syntaxes but it does not guarantee that it is safe to use them as blocklists. so nothing to fix here
