### ISSUE TITLE
add mail_tracking category

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/cname-trackers#85]
We need to allocate a group for trackers used in email. This will help better manage these trackers and protect privacy in email services.
**Problem:**
Blocking the tracker completely would prevent the user from clicking on links in emails, which would degrade the user experience. Instead, blocking only the tracking pixel allows to preserve mail functionality while protecting the user from unwanted monitoring. 
**Suggestion:**
To block the tracking pixel in the mail, we need to create rules, for the ad blocker, that will aim to block only pictures. So, we need to create a separate `mail_tracking` category and add an ad blocker rules sheet for this category
**Important addition:** 
Inserting images in the mail client is done via proxy, so we should not create rules as domain specific.
**Suggestion rule format:**
examle.com$image

**Comment by ameshkov** [comment]
We'll need examples of such trackers

**Comment by jellizaveta** [comment]
### Tracker: **[thirdparty.bnc.lt](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/clickthroughs/branch_io.txt)**

- Company: **Spotify**
- CNAME: [wl.spotify.com](http://wl.spotify.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ;; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;wl.spotify.com.			IN CNAME.
    ;; ANSWER SECTION:
    wl.spotify.com.		110 IN CNAME thirdparty.bnc.lt.
    ```
    
- Pixel in email client: https://ci6.googleusercontent.com/proxy/.....https://wl.spotify.com/ss/o/...../ho.gif

### Tracker: **[cordial.io](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/cordial.txt)**

- Company: **Forbes.com**
- CNAME: [e.email.forbes.com](http://e.email.forbes.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;[e.email.forbes.com](http://e.email.forbes.com/).		IN CNAME.
    ;; ANSWER SECTION:
    [e.email.forbes.com](http://e.email.forbes.com/).	600 IN CNAME [cname.cordial.com](http://cname.cordial.com/).
    ```
    
- Pixel in the email client:
https://ci3.googleusercontent.com/proxy/.....#https://e.email.forbes.com/o/p/

<details><summary>Screenshot:</summary>

![forbes_pxl](https://github.com/AdguardTeam/cname-trackers/assets/91964807/2b241dc9-c725-4f15-8940-1cf35fb3cf0d)

</details><br/>

### Tracker: **[sailthru.com](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/sailthru.txt)**

- Company: **Dwell**
- CNAME: [link.dwell.com](http://link.dwell.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;[link.dwell.com](http://link.dwell.com/).			IN CNAME.
    ;; ANSWER SECTION:
    [link.dwell.com](http://link.dwell.com/).		300 IN CNAME [cb.sailthru.com](http://cb.sailthru.com/).
    ```
    
- Pixel in email client: https://ci5.googleusercontent.com/proxy/.....#https://link.dwell.com/img/650c3b150b34d30db7013b35jlr7j.appb/......gif

---

- Company: **Pet Supermarket**
- CNAME: [link.pet-supermarket.co.uk](http://link.pet-supermarket.co.uk/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;[link.pet-supermarket.co.uk](http://link.pet-supermarket.co.uk/).	IN CNAME.
    ;; ANSWER SECTION:
    [link.pet-supermarket.co.uk](http://link.pet-supermarket.co.uk/). 300 IN CNAME [cb.sailthru.com](http://cb.sailthru.com/).
    ```
    
- Pixel in email client: https://ci4.googleusercontent.com/proxy/.....#https://link.pet-supermarket.co.uk/img/......gif


---


- Company: **Blockworks**
- CNAME: [link.blockworks.co](http://link.blockworks.co/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ;; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;[link.blockworks.co](http://link.blockworks.co/).		IN CNAME.
    ;; ANSWER SECTION:
    [link.blockworks.co](http://link.blockworks.co/).	300 IN CNAME [cb.sailthru.com](http://cb.sailthru.com/).
    ```
    
- Pixel in the email client: 
https://ci4.googleusercontent.com/proxy/.....#https://link.blockworks.co/img/...../8401ea07.gif 
    
### Tracker: **[customer.io](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/customer_io.txt)**


- Company: **imagify.io**
- CNAME: [email.imagify.io](http://email.imagify.io/)


```jsx
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;[email.imagify.io](http://email.imagify.io/).		IN CNAME.
;; ANSWER SECTION:
[email.imagify.io](http://email.imagify.io/).	3600 IN CNAME [e.customeriomail.com](http://e.customeriomail.com/).
```


- Pixel in the email client:
https://ci3.googleusercontent.com/proxy/.....#http://email.imagify.io/e/o/


---


> You can see from the examples that pixels are proxied by email providers,
which is problematic because of the way proxies work. In Gmail, these domains don't even show up at the network level. But, extensions can see them (Gmail puts the actual URL in the location.hash part of src)
>

**Comment by jellizaveta** [comment]
### Tracker: **[thirdparty.bnc.lt](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/clickthroughs/branch_io.txt)**

- Company: **Spotify**
- CNAME: [wl.spotify.com](http://wl.spotify.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ;; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;wl.spotify.com.			IN CNAME.
    ;; ANSWER SECTION:
    wl.spotify.com.		110 IN CNAME thirdparty.bnc.lt.
    ```
    
- Pixel in email client: https://ci6.googleusercontent.com/proxy/.....https://wl.spotify.com/ss/o/...../ho.gif

### Tracker: **[cordial.io](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/cordial.txt)**

- Company: **Forbes.com**
- CNAME: [e.email.forbes.com](http://e.email.forbes.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;e.email.forbes.com.		IN CNAME.
    ;; ANSWER SECTION:
    e.email.forbes.com.	600 IN CNAME cname.cordial.com.
    ```
    
- Pixel in the email client:
https://ci3.googleusercontent.com/proxy/.....#https://e.email.forbes.com/o/p/

<details><summary>Screenshot:</summary>

![forbes_pxl](https://github.com/AdguardTeam/cname-trackers/assets/91964807/2b241dc9-c725-4f15-8940-1cf35fb3cf0d)

</details><br/>

### Tracker: **[sailthru.com](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/sailthru.txt)**

- Company: **Dwell**
- CNAME: [link.dwell.com](http://link.dwell.com/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;link.dwell.com.			IN CNAME.
    ;; ANSWER SECTION:
    link.dwell.com.		300 IN CNAME cb.sailthru.com.
    ```
    
- Pixel in email client: https://ci5.googleusercontent.com/proxy/.....#https://link.dwell.com/img/650c3b150b34d30db7013b35jlr7j.appb/......gif

---

- Company: **Pet Supermarket**
- CNAME: [link.pet-supermarket.co.uk](http://link.pet-supermarket.co.uk/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;link.pet-supermarket.co.uk.	IN CNAME.
    ;; ANSWER SECTION:
    link.pet-supermarket.co.uk. 300 IN CNAME cb.sailthru.com.
    ```
    
- Pixel in email client: https://ci4.googleusercontent.com/proxy/.....#https://link.pet-supermarket.co.uk/img/......gif


---


- Company: **Blockworks**
- CNAME: [link.blockworks.co](http://link.blockworks.co/)
    
    ```jsx
    ;; OPT PSEUDOSECTION:
    ;; EDNS: version: 0, flags:; udp: 1232
    ;; QUESTION SECTION:
    ;link.blockworks.co.		IN CNAME.
    ;; ANSWER SECTION:
    link.blockworks.co.	300 IN CNAME cb.sailthru.com.
    ```
    
- Pixel in the email client: 
https://ci4.googleusercontent.com/proxy/.....#https://link.blockworks.co/img/...../8401ea07.gif 
    
### Tracker: **[customer.io](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/mail_trackers/customer_io.txt)**


- Company: **imagify.io**
- CNAME: [email.imagify.io](http://email.imagify.io/)


```jsx
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;email.imagify.io.		IN CNAME.
;; ANSWER SECTION:
email.imagify.io.	3600 IN CNAME e.customeriomail.com.
```


- Pixel in the email client:
https://ci3.googleusercontent.com/proxy/.....#http://email.imagify.io/e/o/


---


> You can see from the examples that pixels are proxied by email providers,
which is problematic because of the way proxies work. In Gmail, these domains don't even show up at the network level. But, extensions can see them (Gmail puts the actual URL in the location.hash part of src)
>

<details><summary>Letters HTML examples:</summary>

[letters.zip](https://github.com/AdguardTeam/cname-trackers/files/12882970/letters.zip)

</details><br/>

**Comment by jellizaveta** [comment]
closed by https://github.com/AdguardTeam/cname-trackers/commit/81fdf5052317d777a16d3c0326b7356a907df2a0
