### ISSUE TITLE
CNAME tracker of infos.metarom.fr

### ISSUE THREAD

**Issue by MetaSeb** [AdguardTeam/cname-trackers#88]
Bonjour,
 
Nous avons eu une remonter de sécurité concernant un de nos enregistrement DNS qui est apparu dans un fichier dans votre dépôt github.

https://github.com/AdguardTeam/cname-trackers/blob/master/data/clickthroughs/pardot_justdomains.txt
 
Visiblement, au vue de l’historique du fichier, le lien en question est apparu la première fois le 04/12/2023.

![image](https://github.com/AdguardTeam/cname-trackers/assets/84465398/33f3019b-21c0-451a-9839-3acd8608e0f6)

Nous avons regardé dans le fichier qui a été actualiser il y a 2 jours :

![image](https://github.com/AdguardTeam/cname-trackers/assets/84465398/fb15666a-4fc8-4114-be32-043abecd33d2)

Dans le cas présent, il s’agit d’un enregistrement CNAME qui a été créer à la demande de Pardot (Salesforces).
 
Ce lien n’a pas vocation à être connu du grand public 😊
 
Que peut-on envisager dans le cas présent ?
 
Merci !

**Comment by slavaleleka** [comment]
please note that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers

and `infos.metarom.fr` is an actual cname for tracker (clickthrough) domain `go.pardot.com`

**Comment by MetaSeb** [comment]
Hello, ok, I understand!
