### ISSUE TITLE
 Removal request - app.powerwatch.io is not a tracking endpoint

### ISSUE THREAD

**Issue by jacksongoode** [AdguardTeam/cname-trackers#89]
https://github.com/AdguardTeam/cname-trackers/blob/15e2b847c07235bc6e0b0eb95e24592cdc9123a4/data/clickthroughs/branch_io.txt#L1292

Not really sure how it got added since this is a private domain for sensor data collection. If there's justification for its submission, I'd be happy to chat about it.

**Comment by slavaleleka** [comment]
please note that **AdGuard cname-trackers** is not a blocklist, it is just a list of cloaked trackers

and `app.powerwatch.io` is an actual cname for clickthrough domain `custom.bnc.lt` used by Branch.io
