### ISSUE TITLE
False Positive? www3.corelight.com 

### ISSUE THREAD

**Issue by BeanBagKing** [AdguardTeam/cname-trackers#9]
Not sure how this one ended up on the list, but I believe it's a false positive. The domain belongs to https://corelight.com/ and hosts things such as http://www3.corelight.com/nsm@home (link on https://corelight.blog/2021/03/15/translating-query-into-action/).

I'm not affiliated with Corelight, just noticed it while scoping out the @home program.

This issue was originally raised here: https://github.com/StevenBlack/hosts/issues/1648

**Comment by slavaleleka** [comment]
note please that **AdGuard cname-trackers** is not a blocklist, it's just a list of cloaked trackers

and yes, `www3.corelight.com` is real cname for tracker `go.pardot.com`

**Comment by BeanBagKing** [comment]
Closing issue, that answers the question.
