### ISSUE TITLE
Wallapop brocken

### ISSUE THREAD

**Issue by tiziodcaio** [AdguardTeam/cname-trackers#90]
It seems to block clear.wallapop.com which blocks wallapop ui.

**Comment by jellizaveta** [comment]
Hello. `LexisNexis Risk Solutions: online-metrix.net` disguised trackers should not be on the blocking list, as they cause a lot of problems with legitimate sites. For this reason, these trackers are not included in the AdGuard Tracking Protection filter. Also this repository is not a blocking list, it automatically generates lists of disguised trackers.
