### ISSUE TITLE
Infojeux.paris.fr is legit

### ISSUE THREAD

**Issue by clementperon** [AdguardTeam/cname-trackers#92]
Hi @jellizaveta ,

My adblocker recently block the https://infojeux.paris.fr which is the official website of the Paris Olympic Games 2024.
 
This line has been added 8month ago:
https://github.com/AdguardTeam/cname-trackers/blame/acbe7c5f466bea819ee6d8128087ba7047c29afe/data/trackers/np6.txt#L1127

**Comment by TPS** [comment]
This is also  added directly to the AG Tracking Protection Filter, not just this `cname` list.

@clementperon IIUC, https://www.paris2024.org/ is the official site.  What's _this_ 1 you've listed?

**Comment by clementperon** [comment]
@TPS sorry indeed this is the site from "Marie de Paris" -> Paris town hall.
It allows Parisian to subscribe to information about Olympic games.

**Comment by jellizaveta** [comment]
@clementperon Hello. The AdGuard cname-trackers repository itself is not a blocklist, it is just a list of cloaked trackers, NP6 cname trackers are included in the AdGuard Tracking Protection Filter and the domain can be unblocked there. But I can't find the specified request on the page, could you please send the web site.
