### ISSUE TITLE
Broken login on magazineluiza.com.br

### ISSUE THREAD

**Issue by fabianski7** [AdguardTeam/cname-trackers#94]
The domain d.mlcdn.com.br seems to be used in some way for authentication when logging in to the application and the website. When it is blocked, you cannot access your account. After adding it to the whitelist, everything works again.

![image](https://github.com/AdguardTeam/cname-trackers/assets/47755037/98dd8d43-13cd-48f7-b4ff-19842d323baf)

![image](https://github.com/AdguardTeam/cname-trackers/assets/47755037/e02d6cd2-6e28-4cc7-befa-ebb9b978a5e3)

**Comment by jellizaveta** [comment]
Hello. The AdGuard cname-trackers repository is not a blocklist, and not all lists provided in the repository can be used as blocklists as it is written in the readme. `online-metrix.net` disguised trackers are not included in the `AdGuard Tracking Protection Filter` as they cause a lot of breakage.

**Comment by TPS** [comment]
@fabianski7 It'd better to complain to whoever's including this list in your adblocker, & to the login site admin themselves.  You're logging in —  why's a _tracker_ needed, anyway?!
