### ISSUE TITLE
Add ability to exclude domains from the lists

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/cname-trackers#96]
Like in `AdGuardSDNSFilter` - `exclusions.txt`, with matching by the text or by regexp.

Some domains in CNAME lists are not used for ads/tracking, or break sites, and they are badfiltered only in `AdguardFilters\SpywareFilter\sections\cname_allowlist.txt` Raw files are included in many third-party filters, and exclusions from `AdguardFilters` are not applied there.

**Comment by slavaleleka** [comment]
**AdGuard cname-trackers** lists is not a blocklists, it is just a lists of cloaked trackers

and if somebody includes some potentially problematic cname domains list into third-party filter for ad blocking, the exclusion should be added somewhere else, but not in the cname-trackers repo

**Comment by Alex-302** [comment]
For example `||medlemskap.fagforbundet.no^` is in our TPF file and in some third-party filters, where
included `https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/microsites/oracle-eloqua.txt`. We can fix only in our filters. We generate a problem, and don't resolve it.

**Comment by slavaleleka** [comment]
> in some third-party filters
the problem is being generated when somebody risks to use non-blocklist file as a blocklist. there is nothing to fix in this repo

**Comment by Alex-302** [comment]
Why then publish something that isn't being maintained?
