### ISSUE TITLE
Add duplicate and redundancy checking

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/cname-trackers#97]
The size of some lists is greatly increased due to the presence of redundant rules.
We need to check rules for redundancy and remove unnecessary ones.

For example:
```
||tracker.example.com^
||sub.domain.tracker.example.com^
||various.subdomains.tracker.example.com^
```
2, 3 are redundant.

and 
```
||www.1016.lookinews.com^
||1016.lookinews.com^
```
The first is redundant.

Online tool
https://abpvn.com/ruleChecker/redundantRuleChecker.html

Code of this tool
[domain_check.zip](https://github.com/AdguardTeam/cname-trackers/files/14976832/domain_check.zip)

**Comment by ameshkov** [comment]
The easiest way would be to use `tsurlfilter` here.

**Comment by slavaleleka** [comment]
is it redundant for Safari browser as well?

**Comment by Alex-302** [comment]
@slavaleleka In Safari `||` matches only one subdomain, as I remember.

**Comment by Alex-302** [comment]
If `3.2.1.sub.domain.com`:
`||sub.domain.com^` - for regular ad blockers
`.sub.domain.com^` - addition only for Safari CB.
It probably doesn't make sense to do that.

**Comment by slavaleleka** [comment]
it makes sense to be done but not in this repo then

**Comment by jellizaveta** [comment]
The task was moved to the appropriate repositories.
https://github.com/AdguardTeam/FiltersRegistry/issues/946
https://github.com/AdguardTeam/FiltersCompiler/issues/217
